### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by BertrandConxy** [Kandy-Peter/leaderboard#4]
Good job @Kandy-Peter  🥇 

## Highlights
- Well structured and understandable codebase 💯 
- Your code is clean
- Best use of Javascript best practices 💯 

I think everything is good so far. Nothing to comment on, just keep it up 😃

**Comment by abdulrahmanshr75** [comment]
Hello @Kandy-Peter ✋ 
you did an awesome job 🔥 
Congratulations on finishing the project 💯
