### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by abdulrahmanshr75** [Kandy-Peter/leaderboard#5]

**Comment by abdulrahmanshr75** [comment]
Hello @Kandy-Peter ✋ 
I see that you have nice code structure and good logic 🔥 
Excellent job 🥇 
Keep up the good work 💯

**Comment by butlermuwo** [comment]
You have done a great job! 💯
Nice UI 🙌.
The project meets all the requirements.
![CongratsMetalMedalGIF](https://user-images.githubusercontent.com/64237087/152939189-386120fd-3828-4587-ac66-a9ab43cb2b4e.gif)
